name: Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # You can specify the Java version you need

      - name: Build with Maven
        run: mvn -B package --file LAB 3/game/pom.xml

      - name: Run Tests
        run: mvn -B test --file LAB 3/game/pom.xml

